version: '2'

services:
  main_server:
    build: . # build from Dockerfile
    command: python main_server.py # command to start container
    volumes:
      - .:/code
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb-sharded
      - mongodb-cfg-primary
      - mongodb-shard0-primary
      - mongodb-shard1-primary
      - mongodb-shard2-primary
    restart: always
  crawler:
    build: .
    command: python crawler.py # command to start container
    volumes:
      - .:/code
    networks:
      - webnet
    env_file:
      - .env
    depends_on:
      - main_server
      - mongodb-sharded
      - mongodb-cfg-primary
      - mongodb-shard0-primary
      - mongodb-shard1-primary
      - mongodb-shard2-primary
    restart: always

  mongodb-sharded:
    image: 'bitnami/mongodb-sharded:4.2'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    volumes:
      - './mongo/data:/bitnami'
    networks:
      - webnet

  mongodb-shard0-primary:
    image: 'bitnami/mongodb-sharded:4.2'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_data:/bitnami'
    networks:
      - webnet

  mongodb-shard1-primary:
    image: 'bitnami/mongodb-sharded:4.2'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard1-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - 'shard1_data:/bitnami'
    networks:
      - webnet

  mongodb-shard2-primary:
    image: 'bitnami/mongodb-sharded:4.2'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard2-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - 'shard2_data:/bitnami'
    networks:
      - webnet


  mongodb-cfg-primary:
    image: 'bitnami/mongodb-sharded:4.2'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg-primary
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - 'cfg_data:/bitnami'
    networks:
      - webnet

volumes:
  shard0_data:
    driver: local
  shard1_data:
    driver: local
  shard2_data:
    driver: local
  cfg_data:
    driver: local

networks:
  webnet: